### ISSUE TITLE
Android 8

### ISSUE THREAD

**Issue by duanniston** [DarkionAvey/AchievementUnlocked-library#4]
This lib not working with android Oreo, this is the error achievement 

`Unable to add window android.view.ViewRootImpl$W@a763ee4 -- permission denied for window type 2002`

**Comment by rockar06** [comment]
When you are debugging your app, you need to set up the permissions for draw over other apps, when you install it from Google Play Store this permission is setted automatically.

You need to go to Settings> Apps> Click Configuration Menu in Toolbar> Special access> Draw over other apps> Click your app and enable the option "Permit drawing over other apps"

In this way, you could make it work

**Comment by DarkionAvey** [comment]
I'm closing this issue since solution has been offered by @rockar06  
I will revise the permission checking step in the library, I thought Settings.canDrawOverlays(context) is enough to check the permission.
